name: Contracts CI

on:
  push:
    paths:
      - ".github/workflows/contracts.yaml"
      - "packages/snfoundry/**"
      - "package.json"
  pull_request:
    branches:
      - main
    paths:
      - "packages/snfoundry/**"

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04]
        node: [lts/*]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable
        working-directory: ./packages/snfoundry

      - name: Install scarb
        uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: ./packages/snfoundry/contracts/.tool-versions
          scarb-lock: ./packages/snfoundry/contracts/Scarb.lock

      - name: Install snfoundry
        uses: foundry-rs/setup-snfoundry@v3
        with:
          tool-versions: ./packages/snfoundry/contracts/.tool-versions

      - name: Check Code Format
        run: yarn format:check

      - name: Build Contracts
        run: yarn compile

      - name: Run Tests
        run: yarn test
