name: Next.js CI

on:
  push:
    paths:
      - ".github/workflows/**"
      - "packages/nextjs/**"
      - "package.json"
  pull_request:
    branches:
      - main
    paths:
      - "packages/nextjs/**"

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04]
        node: [lts/*]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"

      - name: Install dependencies (Next.js)
        run: yarn install --immutable
        working-directory: ./packages/nextjs

      - name: Install scarb
        uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: ./packages/snfoundry/contracts/.tool-versions
          scarb-lock: ./packages/snfoundry/contracts/scarb.lock

      - name: Check Code Format
        run: yarn format:check

      - name: Run Next.js lint
        run: yarn next:lint --max-warnings=0

      - name: Check typings on Next.js
        run: yarn next:check-types

      - name: Build Next.js project
        run: yarn next:build

      - name: Run Next.js Tests
        run: yarn next:test
